Feature/generate unit test data2
dnWalker-project/dnWalker pull request #6
Opened 2021-11-02 08:23 UTC by benjamin-hejl

2021-11-19 06:20 UTC, kfrajtak requested changes

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker.TestGenerator/test_data.xml
> +                <Int32Parameter Name="x" Value="-5"/>
Lepsi bude mit obecny parametr a u nej atribut s typem.

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker/Concolic/XmlExplorationExporter.cs
> +            _currentExplorationElement.SetAttributeValue("assembly-name", e.AssemblyName);
bez pomlcek

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker.TestGenerator.Tests/CodeWriterTests.cs
> +            writer.ToString().Should().Be(CodeTexts.Assign_5_To_X);
nepouzivejte resx soubor, napiste to rovnou sem

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker/Concolic/XmlExplorationExporter.cs
> +        void HookUp(Explorer2 explorer);
prejmenovat na `Register`

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker/Concolic/XmlExplorationExporter.cs
> +    public interface IExplorationExporter
prejmenovat na `IExplorationExtension`

2021-11-19 06:20 UTC, kfrajtak commented on Examples/TestGeneration/Instance/ObjectAndPrimitiveArgs.cs
> +            public int Id
lze zapsat jako public int Id { get; set; }, pak je vygenerovan (v c#) backing field
bude to fungovat?

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker.Parameters.Tests/Xml/SerializationTestDataProvider.cs
> +                parameter = new BooleanParameter("My:Boolean:Parameter", true);
jaky je ucel?

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker.Parameters/ArrayParameter.cs
> +        protected override void OnNameChanged(String newName)
pridat komentare

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker.TestGenerator/CodeWriter.cs
> +    public class CodeWriter : IDisposable
je tohle jeste potreba, kdyz se pouzivaji T4 sablony?

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker.TestGenerator/Explorations/ExplorationData.cs
> +            ExplorationData ed = new ExplorationData();
ed => explorationData

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker.TestGenerator/Explorations/ExplorationData.cs
> +            ed._assemblyName = xml.Attribute("AssemblyName")?.Value ?? throw new Exception("Exploration data XML must contain 'AssemblyName' attribute.");
pouzivejte nameof
proc se inicialuzuji primo fieldy?
musi to byt staticka metoda?
neslo by to resit deserializaci?

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker.TestGenerator/Explorations/ExplorationData.cs
> +            ExplorationIterationData eid = new ExplorationIterationData();
vhodnejsi by bylo to inicializovat pres parametry konstruktoru

2021-11-19 06:20 UTC, kfrajtak commented on dnWalker.TestGenerator/XUnit/XUnitTestClassWriter.cs
> +            _leaveOpen = leaveOpen;
pridat komentar

2021-11-19 08:59 UTC, benjamin-hejl commented on Examples/TestGeneration/Instance/ObjectAndPrimitiveArgs.cs
> +            public int Id
fungovat by to mělo, ale chci mít jistotu, jak se ty fieldy jmenují

2021-11-19 09:01 UTC, benjamin-hejl commented on dnWalker.Parameters.Tests/Xml/SerializationTestDataProvider.cs
> +                parameter = new BooleanParameter("My:Boolean:Parameter", true);
generuje to test cases pro otestování XML (de)serializace parametrů, použijí se v testech XmlDeserializerTests a XmlSerializerTests

2021-11-22 10:02 UTC, benjamin-hejl commented on dnWalker.TestGenerator/test_data.xml
> +                <Int32Parameter Name="x" Value="-5"/>
ano, v nové verzi to tak je

2021-11-22 10:03 UTC, benjamin-hejl commented on dnWalker.TestGenerator/CodeWriter.cs
> +    public class CodeWriter : IDisposable
třída odebrána

2021-11-22 10:04 UTC, benjamin-hejl commented on dnWalker.TestGenerator/Explorations/ExplorationData.cs
> +            ed._assemblyName = xml.Attribute("AssemblyName")?.Value ?? throw new Exception("Exploration data XML must contain 'AssemblyName' attribute.");
udělal jsem to jako extension method pro XElement v samostatné třídě

2021-11-23 15:23 UTC, merged